# Generated by Django 4.0.5 on 2022-06-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SM', 'Sport wear'), ('OW', 'Outwear')], default=(), max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='lable',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary'), ('D', 'danger')], default=(), max_length=1),
        ),
    ]
