# Generated by Django 4.0.5 on 2022-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='lable',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary'), ('D', 'danger')], default=False, max_length=1),
        ),
    ]
